# https://docs.netlify.com/configure-builds/file-based-configuration/
# testing uwu

[build]
publish = "public/"
command = "yarn build"

[build.environment]
TZ = "America/Los_Angeles"
CI = "true"

[context.production]
ignore = "true"
