# https://docs.netlify.com/configure-builds/file-based-configuration/
# testing uwu

[build]
command = "vite build"
publish = "dist"

[build.environment]
TZ = "America/Los_Angeles"
CI = "true"

[context.production]
ignore = "true"

[[redirects]]
  from = "/blog/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
