import { mkdir, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';
import { officers } from '../src/data/profiles.js';

const sourceRoot = new URL('../src/images/', import.meta.url);
const outputRoot = new URL('optimized/', sourceRoot);
let totalBytes = 0;
let imageCount = 0;

async function optimize(source, folder, id, widths, square) {
	await mkdir(new URL(`${folder}/`, outputRoot), { recursive: true });
	const image = sharp(fileURLToPath(new URL(source, sourceRoot))).rotate();
	const { autoOrient } = await image.metadata();
	const maxWidth = square ? Math.min(autoOrient.width, autoOrient.height) : autoOrient.width;
	const outputWidths = [...new Set(widths.map(width => Math.min(width, maxWidth)))];
	const variants = [];
	for (const width of outputWidths) {
		const filename = `${folder}/${id}-${width}.webp`;
		const info = await image.clone()
			.resize({ width, ...(square ? { height: width, fit: 'cover' } : {}) })
			.webp({ quality: 80 })
			.toFile(fileURLToPath(new URL(filename, outputRoot)));
		totalBytes += info.size;
		imageCount++;
		variants.push({ filename, width: info.width, height: info.height });
	}
	const url = variant => `new URL('./${variant.filename}', import.meta.url).href`;
	const defaultImage = variants.at(-1);
	return `{ src: ${url(defaultImage)}, srcSet: [${variants.map(variant => `${url(variant)} + ' ${variant.width}w'`).join(', ')}].join(', '), width: ${defaultImage.width}, height: ${defaultImage.height} }`;
}

const portraits = [];
for (const { id } of officers) {
	const normal = await optimize(`team/${id}.jpg`, 'team', id, [200, 400, 600], true);
	const alternate = await optimize(`team-easter-egg/${id}.jpg`, 'team-easter-egg', id, [200, 400, 600], true);
	portraits.push(`${JSON.stringify(id)}: { normal: ${normal}, alternate: ${alternate} }`);
}

const gallery = [];
for (let index = 1; index <= 8; index++) {
	gallery.push(await optimize(`carousel/image${index}.jpg`, 'carousel', `image${index}`, [640, 1280, 1920], false));
}

await writeFile(new URL('images.js', outputRoot),
	`// Generated by npm run images. Edit the original photos, not this file.\nexport const portraits = {\n${portraits.join(',\n')}\n};\nexport const gallery = [\n${gallery.join(',\n')}\n];\n`);
console.log(`Generated ${imageCount} WebP variants (${(totalBytes / 1e6).toFixed(2)} MB total).`);
